name: arcgis
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - arcgis=2.0.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asgiref=3.6.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.11.2
  - bleach=6.0.0
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - django=4.1.7
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - flit-core=3.8.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - greenlet=2.0.2
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.0.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jaraco.classes=3.2.3
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.2
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.6
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.5
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.12
  - libffi=3.4.2
  - libglib=2.74.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.39
  - libpq=15.1
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2022.1.0
  - more-itertools=9.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.24.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openpyxl=3.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - ply=3.11
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pyspnego=0.3.0
  - python=3.9.0
  - python-certifi-win32=1.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.6
  - python_abi=3.9
  - pytz=2022.7.1
  - pywin32=304
  - pywin32-ctypes=0.2.0
  - pywin32-security=302
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qt-main=5.15.6
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - requests=2.28.2
  - requests-kerberos=0.12.0
  - requests-negotiate-sspi=0.5.3
  - requests-oauthlib=1.3.1
  - requests-toolbelt=0.10.1
  - requests_ntlm=1.2.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - send2trash=1.8.0
  - setuptools=67.4.0
  - sip=6.7.7
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.4
  - sqlite=3.40.0
  - sqlparse=0.4.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - terminado=0.17.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - ujson=5.7.0
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winkerberos=0.9.1
  - winpty=0.4.3
  - wrapt=1.14.1
  - xlrd=2.0.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.14.0
  - zstd=1.5.2
  - pip:
      - psycopg2==2.9.5
